### ISSUE TITLE
Support for maplibre-gl@2.0.x

### ISSUE THREAD

**Issue by dreamorosi** [aws-amplify/maplibre-gl-js-amplify#107]
With this issue I'd like to request to consider supporting `maplibre-gl@2.0.x`.

At the moment, as you know, the library enforces `maplibre-gl@1.x` at least from the outside, this is for no apparent reason.

Just for reference, [I've create a sample demo](https://github.com/dreamorosi/react-map-gl-7-test) that uses `react-map-gl` with Amplify Geo and `AmplifyMapLibreRequest` and forced version `2.0.x` of `maplibre-gl` and I'm still able to use `AmplifyMaplibreRequest`.

Before opening this issue I've tried to clone the repo, upgrade to `maplibre-gl@2.0.x` and saw that there are parts, like the ones related to geofences that are not compatible out-of-the-box so I'm not expecting any overnight change nor commitment.

The only thing I'd like to do with this issue is to ask you if you'll consider supporting this newer version.

**Comment by thaddmt** [comment]
Yep this is definitely on our calendars! We're working on a few things now but want to make sure we full test maplibre-gl@2 with this plugin before we release it though I do believe it should be relatively safe

**Comment by reesscot** [comment]
@dreamorosi This upgrade has been released for a bit now, so closing this out
