### ISSUE TITLE
markerimageElement isn't working

### ISSUE THREAD

**Issue by shafkevi** [aws-amplify/maplibre-gl-js-amplify#128]
I'm using the .html loaded versions of this library, and whenever I try to load an image as my marker, I just get the default.
I can easily create an image and just load it in the page by injecting it to the <body>, but haven't been able to get the icon working for me. My goal is to have a distinct icon per point (basically a thumbnail picture of a person), and was planning to drawPoints multiple times to do that, but if I could feed in the marker details where I have title/address/coordinates that would be great too.

```
                    const peopleMap = await createMap(
                        {
                            container: "peopleMap",
                            center: [-101.8151056, 36.2153979],
                            zoom: 3,
                        }
                    );
                    people = [{coordinates: [lon,lat], title: "hello", address: "there"}],
                    const myImg = new Image();
                    myImg.src = 'https://pathToMyImage.com/foobarbazImage;
                    myImg.alt = "myImage";
                    drawPoints(
                        "people",
                        people,
                        peopleMap, 
                        {
                            "unclusteredOptions": {
                                "markerimageElement": myImg
                            }
                        }
                    );
```

```
    <script src="https://cdn.amplify.aws/packages/maplibre-gl/1.15.2/maplibre-gl.js" integrity="sha384-rwYfkmAOpciZS2bDuwZ/Xa/Gog6jXem8D/whm3wnsZSVFemDDlprcUXHnDDUcrNU" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.amplify.aws/packages/core/4.3.0/aws-amplify-core.min.js" integrity="sha384-7Oh+5w0l7XGyYvSqbKi2Q7SA5K640V5nyW2/LEbevDQEV1HMJqJLA1A00z2hu8fJ" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.amplify.aws/packages/auth/4.3.8/aws-amplify-auth.min.js" integrity="sha384-jfkXCEfYyVmDXYKlgWNwv54xRaZgk14m7sjeb2jLVBtUXCD2p+WU8YZ2mPZ9Xbdw" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.amplify.aws/packages/geo/1.1.0/aws-amplify-geo.min.js" integrity="sha384-TFMTyWuCbiptXTzvOgzJbV8TPUupG1rA1AVrznAhCSpXTIdGw82bGd8RTk5rr3nP" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.amplify.aws/packages/maplibre-gl-js-amplify/1.1.0/maplibre-gl-js-amplify.umd.min.js" integrity="sha384-7/RxWonKW1nM9zCKiwU9x6bkQTjldosg0D1vZYm0Zj+K/vUSnA3sOMhlRRWAtHPi" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.amplify.aws/packages/maplibre-gl-geocoder/1.1.0/maplibre-gl-geocoder.min.js" integrity="sha384-kB2/fEHOpfHm1Gzute77/GLQw40BlWkV4XCaqQ/+P8zPIwUm4X5gZxcYx7Nj3tpC" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link href="https://cdn.amplify.aws/packages/maplibre-gl-geocoder/1.1.0/maplibre-gl-geocoder.css" rel="stylesheet" integrity="sha384-9INm4qwCgRPHsynDw8uatP2FHVIMItwPU+PH8RtOzYAGEjU4Hiirfmuc3Rsa/pBq" crossorigin="anonymous" referrerpolicy="no-referrer"></link>
    <link href="https://cdn.amplify.aws/packages/maplibre-gl/1.15.2/maplibre-gl.css" rel="stylesheet" integrity="sha384-DrPVD9GufrxGb7kWwRv0CywpXTmfvbKOZ5i5pN7urmIThew0zXKTME+gutUgtpeD" crossorigin="anonymous" referrerpolicy="no-referrer"></link>
```

**Comment by AuboIoT** [comment]
I've got a similar problem. In my case working with React.
I'm trying to use **drawPoints()** to draw custom icons. I've follow the guide but it's stil showing the default icons. 
First I imported the library and the icon.
```
import { drawPoints } from "maplibre-gl-js-amplify";
import CustomIcon from 'assets/Aubo-logo.png';

```
Then I declared this, as the documentation mentioned (I try it declaring it at the beginning of the script right after the import of libraries, and also right before the map.on("load",....), but same result.
```
//custom icon
const icon = new Image(100,100);
icon.src = CustomIcon;
```
Then I declared a functional component (React), and inside the useEffect() hook after creating the map I load this. 
![image](https://user-images.githubusercontent.com/94767041/160442316-4bbc32d9-314d-4fb3-bd85-e85870a8155f.png)
I'm passing it the icon object that I declared at the beginning, but it shows the default icons? Why is this happening? or What am I doing wrong? Thanks. 
![image](https://user-images.githubusercontent.com/94767041/160442376-366e9617-2ce0-4919-b607-4068ed0999e3.png)

**Comment by thaddmt** [comment]
@AuboIoT this update hasn't been released to NPM yet but it is available on the unstable release - https://github.com/aws-amplify/maplibre-gl-js-amplify/releases/tag/v1.3.0-unstable.1

@shafkevi this may be due to the html loaded version not having the latest release, will look into this, thanks for bringing it up!

**Comment by sreeramsama** [comment]
Verified that custom icons can now be shown on a map after above merge.

<img width="300" alt="SCR-20221219-hm5" src="https://user-images.githubusercontent.com/12038441/208531486-79362c21-65e0-4a82-8f9c-f4a3f6e164c4.png">

**Comment by sreeramsama** [comment]
@AuboIoT, @shafkevi 
Please verify if it works on your side so we can close the issue.
