### ISSUE TITLE
React Warnings when using Amplify MapView Component

### ISSUE THREAD

**Issue by thaddmt** [aws-amplify/maplibre-gl-js-amplify#147]
## Issue
When using the new Amplify UI `MapView` component with a CRA there are some warnings thrown that reference failing to parse source map from a file in `maplibre-gl-js-amplify`.

## Probably root cause
Currently our prod bundle includes source maps which links to .ts files which are not included in the bundle. This causes a lot of warnings during builds in react (screenshot below). UI team faced a similar issue and simply turned off source maps (https://github.com/aws-amplify/amplify-ui/pull/1608)

## Potential Solutions
Source maps should be turned off in prod (maybe in dev as well).

<img width="1022" alt="Screen Shot 2022-04-06 at 11 46 33 AM" src="https://user-images.githubusercontent.com/68032955/162526500-4018177e-9803-47eb-97ca-9d56652be31f.png">

In the short term customers can also probably run `yarn start` or `npm run start` with `GENERATE_SOURCEMAP=false`. This seems to be a pervasive issue with many CRA5 applications - https://github.com/facebook/create-react-app/discussions/11767

**Comment by thaddmt** [comment]
PR to remove source maps - https://github.com/aws-amplify/maplibre-gl-js-amplify/pull/145

Still needs to be released to `latest` and added to the Amplify UI `MapView` component to fix the warnings

**Comment by slaymance** [comment]
We've bumped the version of the Amplify UI dependency with [PR 1721](https://github.com/aws-amplify/amplify-ui/pull/1721) and the fix can be found in [@aws-amplify/ui-react@2.15.4](https://github.com/aws-amplify/amplify-ui/releases/tag/%40aws-amplify%2Fui-react%402.15.4). We can consider this issue closed now.
