### ISSUE TITLE
AmplifyMapLibreRequest signature not working on S3 static site

### ISSUE THREAD

**Issue by jcary741** [aws-amplify/maplibre-gl-js-amplify#170]
I have a S3 bucket with static site hosting enabled, but cannot fetch tiles from it, and instead get the response:
```
404 Not Found
Code: UnsupportedQuery
Message: The request contained an unsupported query string parameter.
ParameterName: x-amz-user-agent
RequestId: T00YZSA7BESS216G
HostId: RZIYEDjn70qk+KUdSOzpM9IgsYiAtVSuGZBv8Bkl4r/OimCgumPf+zVRsn1Xwv6O2976jFMYB2Y=
```

Tracking this down, I believe it is referring to [this line](https://github.com/aws-amplify/maplibre-gl-js-amplify/blob/main/src/AmplifyMapLibreRequest.ts#L122), which is including a header that S3 doesn't like.

**Comment by sreeramsama** [comment]
Can you share more details on your implementation? Did you use vector or raster tile source?

**Comment by sreeramsama** [comment]
Closing as this is pending response since two weeks.
