### ISSUE TITLE
Creating map with bounds not working

### ISSUE THREAD

**Issue by andrew-g-mcdonald** [aws-amplify/maplibre-gl-js-amplify#172]
**maplibre-gl-js-amplify**: ^2.0.4
**maplibre-gl**: ^2.3.0

Calling createMap with a bounds property (either an array of LngLatLike or the LngLatBounds object `new maplibregl.LngLatBounds`) results in the map being drawn at max zoom (basically the entire Earth). If I call map.fitBounds after creation and pass in the same bounds object the map moves/zooms appropriately.

**Comment by sreeramsama** [comment]
Please try using ``maxBounds`` as in example here https://maplibre.org/maplibre-gl-js-docs/example/restrict-bounds/
Verified that this works with ``createMap`` of ``maplibre-gl-js-amplify``.
