### ISSUE TITLE
Can't set marker colors

### ISSUE THREAD

**Issue by ffxsam** [aws-amplify/maplibre-gl-js-amplify#191]
I can't seem to find a way to set marker colors. Everything else is customizable except for this.

I can change the marker opacity level, no problem:
```js
map.setPaintProperty('my-points-layer-unclustered-point', 'icon-opacity', 0.5)
```
But this has no effect:
```js
map.setPaintProperty('my-points-layer-unclustered-point', 'icon-color', '#f00')
```

**Comment by sreeramsama** [comment]
Can you share more details on how these markers are created, and how they are related to the layer `my-points-layer-unclustered-point`?

**Comment by ffxsam** [comment]
@sreeramsama I was using this library's `drawPoints` to draw the points. The layer name (`my-points-layer-unclustered-point`) is determined by that function.

But no worries, I took a different approach and am using maplibre's `Marker` and `Point` classes to manually add markers to a map and style them.

**Comment by sreeramsama** [comment]
Great!
With `Marker` class, `new mapboxgl.Marker({ "color": "#f00" })` creates a new marker object with #f00 color and this can then be added to a map using the ``addTo()`` method.
